config/routes.rb
EChallenge::Application.routes.draw do
  root :to => redirect('/members')
  resources :members, except: [:edit, :destroy] do
    post 'add_friend/:id' => 'members#add_friend', as: :add_friend
    match 'find_experts' => 'members#find_experts', via: [:get, :post], as: :find_experts
  end

  get '/:id' => "shortener/shortened_urls#show", as: :shortener

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :member
  belongs_to :friend, class_name: 'Member'

  validate :check_ids

  after_create :update_counter_cache
  after_destroy :update_counter_cache

  private
  def check_ids
    errors.add(:member_id, 'wrong order of ids') unless member_id < friend_id
  end

  def update_counter_cache
    if self.destroyed?
      [member_id, friend_id].each do |i|
        Member.decrement_counter(:friends_count, i)
      end
    else
      [member_id, friend_id].each do |i|
        Member.increment_counter(:friends_count, i)
      end
    end
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :topics, dependent: :delete_all
  has_many :friendships
  #has_many :friends, through: :friendships
  has_shortened_urls

  validate :valid_url

  after_create :create_short_url, :create_topics

  scope :by_create, -> { order('created_at DESC') }
  scope :by_friends, -> { order('friends_count DESC') }

  def friends
    Member.joins('INNER JOIN friendships ON members.id = friendships.friend_id OR members.id = friendships.member_id').
        where('(friendships.member_id = :id OR friendships.friend_id = :id) AND members.id != :id',:id => self.id).
        by_friends.where(nil)
  end

  def add_friend(friend)
    ids = [self.id, friend.id].sort
    fs = Friendship.new(member_id: ids.first, friend_id: ids.last)
    fs.save
  end

  def short_url_key
    shortened_urls.last.try(:unique_key)
  end

  def create_topics
    get_topics.each do |t|
      self.topics.create!(level: t[:level], title: t[:title]) unless t[:title].blank?
    end
  end

  def get_topics
    res = []
    require 'open-uri'
    n = Nokogiri::HTML(open(website))
    n.css('h1,h2,h3').each do |node|
      level = node.name[/\d/].to_i
      res << {level: level, title: node.text.strip}
    end
    res
  rescue OpenURI::HTTPError, SocketError
    res
  end

  #def update_friends_count
  #  self.update_attributes(friends_count: friends.count)
  #end

  private
  def valid_url
    if self.website
      unless UrlValidator.valid?(self.website)
        errors.add(:website, 'Not valid url, please check website address')
      end
    end
  end

  def create_short_url
    Shortener::ShortenedUrl.generate(website, self)
  end


  #def increment_counter
  #  self.update_attributes(friends_count: friends_count+1)
  #end
  #
  #def decrement_counter
  #  self.update_attributes(friends_count: friends_count-1)
  #end

  #def add_http
  #  if website
  #    new_website = "http://#{website}" unless website =~ /\Ahttp(s)?:\/\//
  #    if UrlValidator.valid?(new_website)
  #      self.website = new_website
  #    end
  #  end
  #end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :level, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 3 }

  belongs_to :member

  scope :by_level, -> { order(:level) }

  def self.search_by_title(title)
    Topic.where('title ILIKE ?', "%#{title}%").where(nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  include MembersHelper

  def index
    @member = Member.new
    @members = Member.includes(:shortened_urls).by_friends.page(params[:page])
  end

  def new
    @member = Member.new
  end

  def show
    @member = Member.find(params[:id])
    @topics = @member.topics.by_level
    @friends = @member.friends
    @not_friends = not_friends

    @title = @member.name
  end

  def create
    @member = Member.new(member_params)
    logger.debug @member.errors.full_messages.inspect
    if @member.save
      redirect_to member_url(@member)
    else
      render :new
    end
  end

  def add_friend
    @member = Member.find(params[:member_id])
    @friend = Member.find(params[:id])
    if @member.add_friend(@friend)
      @friends = @member.friends
      @not_friends = not_friends
      respond_to do |format|
        format.js
      end
    else
      render nothing: true, status: 400
    end
  end

  def find_experts
    @member = Member.find(params[:member_id])
    @result = []

    if params[:title].present?
      @topics = Topic.search_by_title(params[:title])
      member_ids = @topics.map(&:member_id).uniq

      bfs = BFS.new
      paths = bfs.bfs(@member.id, *member_ids)

      if paths
        @members = Member.find(paths.flatten.uniq)
        @topics.each do |t|
          path = paths.find{|f| f.last == t.member_id}
          if path
            members_path = path.map{|id| @members.find{|f| f.id == id} }
            @result << { path: members_path, topic: t, names: members_path.map(&:name)}
          end
        end
        @result = sort_experts(@result)
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def member_params
    params.require(:member).permit(:name, :website)
  end

  def not_friends
    Member.where('id NOT IN (?)', @friends.map(&:id) << @member.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def sort_experts(result)
    #Sort result by deep, heading level
    result.sort do |x,y|
      x_count = x[:path].count
      y_count = y[:path].count
      if x_count == y_count
        x[:topic].level <=> y[:topic].level
      else
        x_count <=> y_count
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evrone Challenge<%= @title ? " - #{@title}" : '' %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/members/_find_experts.html.haml
- if @result.blank?
  = t('expert.not_found')
- @result.each do |h|
  %p
    - links = h[:path].map do |member|
      - link_to member.name, member_path(member)
    != links.join(' -> ')

    -# h[:names].join(' -> ')
    = "(\"#{h[:topic].title}\")"

app/views/members/_friends.html.haml
- if @friends.blank?
  %h2= t('friend.blank')
- else
  %h2= t('word.friends')
  %ol
    - @friends.each do |f|
      %li
        = link_to f.name, member_path(f)
- unless @not_friends.blank?
  %h3= t('friend.add')
  - @not_friends.each do |member|
    %p= link_to member.name, member_add_friend_path(@member, member), remote: true, method: :post

app/views/members/_new.html.haml
.new_member
  = simple_form_for @member do |f|
    = f.input :name, label: false, placeholder: Member.human_attribute_name(:name)
    = f.input :website, label: false, placeholder: Member.human_attribute_name(:website)
    = f.submit

app/views/members/add_friend.js.erb
$('.friends').html('<%= j(render partial: 'friends') %>')

app/views/members/find_experts.html.haml
= render 'find_experts'

app/views/members/find_experts.js.erb
$('.list-experts').html('<%= j(render partial: 'find_experts') %>')

app/views/members/index.html.haml
= render 'new'

.member_list
  - @members.each do |member|
    .member
      %p
        %h2.member_name
          = link_to member.name, member_path(member)
          %span.friends_count= member.friends_count
        - short_url = shortener_url(member.short_url_key)
        = link_to short_url, short_url, target: '_blank'

= paginate @members

app/views/members/new.html.haml
= render 'new'

app/views/members/show.html.haml
%h1.member_name.center= @member.name
%span= link_to @member.website, @member.website, target: '_blank'
- short_url = shortener_url(@member.short_url_key)
%span.member-short_url= link_to short_url, short_url, target: '_blank'

.topics
  - if @topics.blank?
    %h2= t('topic.blank')
  - else
    %h2= Topic.model_name.human(count: 3)
    %ul
      - @topics.each do |t|
        %li
          = t.title
          = "(#{t.level})"


.friends
  = render 'friends'
.find-expert
  %h2= t('expert.find')
  = form_tag member_find_experts_path(@member), remote: true do
    = text_field_tag 'title'
    = submit_tag t('word.search')
.list-experts